[package]
name = "bevy_egui_ecs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
nightly = []

[dependencies]
bevy = { version = "0.11", default-features = false }
bevy_egui = "0.21"